// Core types for Wraith Protocol

export interface WraithConfig {
  adapter: 'strk20' | 'privacy-pools';
  starknetRpcUrl?: string;
  litNetwork?: 'datil' | 'cayenne' | 'manzano';
  storachaEmail?: string;
  settlementFeeBps?: number; // default 10 (0.1%)
  /** ERC-8004 agent identity config. Enables receipt generation after payments. */
  erc8004?: {
    name: string;
    description: string;
    ethAddress?: string;
    starknetAddress?: string;
    agentId?: number;
    registryAddress?: string;
  };
}

export interface Note {
  secret: bigint;
  nullifier: bigint;
  amount: bigint;
  token: string; // contract address
  spent: boolean;
}

export interface PaymentIntent {
  url: string;
  amount: bigint;
  token: string; // 'USDC', 'STRK', or contract address
  maxLatencyMs?: number; // default 5000
}

export interface PaymentReceipt {
  txHash: string;
  timestamp: number;
  amount: bigint;
  token: string;
  apiUrl: string;
  encrypted: boolean; // stored in Storacha if true
  cid?: string;        // Filecoin CID if encrypted
}

export interface PrivacyScore {
  adapter: string;
  depositorVisible: boolean;
  proofSystem: 'groth16' | 'stark' | 'plonk';
  quantumResistant: boolean;
  anonymitySetSize: number | 'unlimited';
  guarantee: 'demo' | 'weak' | 'strong' | 'zk-native';
  recommendation?: string;
}

export interface AuditProof {
  viewingKey: string;
  payments: PaymentReceipt[];
  totalAmount: bigint;
  timeRange: { from: number; to: number };
  proof: string; // serialized ZK proof
}

// Adapter interface - every backend implements this
export interface IPrivacyAdapter {
  name: string;
  getPrivacyScore(): PrivacyScore;

  // deposit into the privacy pool / shield tokens
  deposit(amount: bigint, token: string): Promise<{ txHash: string; note: Note }>;

  // withdraw from pool / unshield tokens to recipient
  // proof: Groth16 proof for PrivacyPoolsAdapter (generated by API server, not agent)
  withdraw(note: Note, recipient: string, proof?: bigint[]): Promise<{ txHash: string }>;

  // for compliance: generate audit proof
  generateAuditProof?(
    viewingKey: string,
    range: { from: number; to: number }
  ): Promise<AuditProof>;
}

// x402 HTTP challenge/response types
export interface X402Challenge {
  scheme: string;
  network: string;
  token: string;
  amount: string;
  payTo: string;
  memo?: string;
}

export interface X402PaymentProof {
  scheme: string;
  network: string;
  txHash?: string;
  depositEvent?: {
    blockNumber: number;
    secretNullifierHash: string;
  };
  secret?: string;        // encrypted, only API can decrypt via Lit
  nullifier?: string;     // encrypted
  litCiphertext?: string; // Lit-encrypted (secret, nullifier) bundle
  /** ERC-8004 agent identity metadata (optional, for receipt generation) */
  agentURI?: string;      // data: URI or IPFS CID of agent registration file
  agentId?: string;       // ERC-8004 agent ID (ERC-721 token ID, if registered)
}
